services:
  # Django Web Service
  - type: web
    name: voucher-app-backend
    runtime: python
    region: oregon
    plan: starter
    branch: main
    buildCommand: "pip install -r backend/requirements.txt && python backend/manage.py collectstatic --no-input && python backend/manage.py migrate"
    startCommand: "gunicorn voucher_project.wsgi:application --chdir backend --bind 0.0.0.0:$PORT"
    healthCheckPath: /api/health/
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: DATABASE_URL
        fromDatabase:
          name: voucher-app-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: voucher-app-redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: FRONTEND_URL
        sync: false

  # Celery Worker
  - type: worker
    name: voucher-app-worker
    runtime: python
    region: oregon
    plan: starter
    branch: main
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "celery -A voucher_project worker --loglevel=info --chdir backend"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: DATABASE_URL
        fromDatabase:
          name: voucher-app-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: voucher-app-redis
          property: connectionString
      - key: SECRET_KEY
        sync: false

  # Celery Beat (Scheduler)
  - type: worker
    name: voucher-app-beat
    runtime: python
    region: oregon
    branch: main
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "celery -A voucher_project beat --loglevel=info --chdir backend"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: DATABASE_URL
        fromDatabase:
          name: voucher-app-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: voucher-app-redis
          property: connectionString
      - key: SECRET_KEY
        sync: false

  # Redis Service
  - type: redis
    name: voucher-app-redis
    region: oregon
    plan: starter
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []

# Database
databases:
  - name: voucher-app-db
    databaseName: voucher_app
    user: voucher_app_user
    region: oregon
    plan: starter
    postgresMajorVersion: "17"
